version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: projectname
      POSTGRES_PASSWORD: "DB_PASSWORD"
    volumes:
      - projectname_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "REDIS_PASSWORD"
    environment:
      - REDIS_REPLICATION_MODE=master
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: projectname
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "MONGODB_PASSWORD"
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - projectname_data:/var/lib/mongodb/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  projectname_data:
