name: Serverpod CI

on:
  push:
    branches:
      - main
      - dev
      - tests
  pull_request:
    branches:
      - main
      - dev
jobs:

  dart_format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  dart_analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
      - name: Install dependencies
        run: util/pub_get_all
      - name: Analyze
        run: util/run_tests_analyze

  single_server_tests:
    name: Single server tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run single server tests
        run: util/run_tests_single_server
